### ISSUE TITLE
Documentation on training

### ISSUE THREAD

**Issue by mrocr** [Verazjy/Document-image-binarization-with-Cascaded-cGANs-generator#1]
@Verazjy Add documentation on preparing training data, and training.

**Comment by Verazjy** [comment]
Thank you for reminding us. We have added training related code. The binarization datasets are public, and the size of these images beyond the upload limit. You can download them on the relevant webpages.

**Comment by hgc666** [comment]
I am very exciting to find someone are doing binarization with GAN, and I am very interested in your project. But I downloaded your project and found that it can't run. It seems that there are some files missing, so I would like to ask you some question. Can you help me? I am looking forward to hearing from you. Thank you so much! （It seems that there is less data folder）

**Comment by justinner** [comment]
Hi, @Verazjy ,when i just want to ru the test_all.py,I did not change the image,just chage the path,the error occured as following:
_PermissionError: [Errno 13] Permission denied: 'D:\\Document-image-binarization-with-Cascaded-cGANs-generator-train\\testimg/'_
could you help me ?Thanks very much.
